name: Terraform - Azure Dev Environment

on:
  push:
    branches:
      - main
      - 'feature/**'
  workflow_dispatch:  # manual trigger support

jobs:
  terraform:
    name: Terraform Dev Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login via GitHub Action (az CLI)
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Terraform Init
        run: terraform init
        working-directory: environments/dev

      - name: Terraform Validate
        run: terraform validate
        working-directory: environments/dev

      - name: Terraform Plan (for feature branches)
        if: startsWith(github.ref, 'refs/heads/feature/')
        run: terraform plan
        working-directory: environments/dev

      - name: Terraform Apply (for main branch)
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
        working-directory: environments/dev
