name: Terraform - Azure CLI Auth for Dev Environment

on:
  push:
    branches:
      - main
      - 'feature/**'
    paths:
      - 'environments/dev/**'  # <-- Fix here

jobs:
  terraform:
    name: Terraform Dev Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: environments/dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login via GitHub Action (az CLI)
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        if: startsWith(github.ref, 'refs/heads/feature/')
        run: terraform plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
